### ISSUE TITLE
How to build from this json

### ISSUE THREAD

**Issue by pankajk2934** [KhaledSMQ/Ng2FormBuilder#1]
Please guide me how to build dynamic form from this JSON
and need "form group" control also

**Comment by KhaledSMQ** [comment]
You can use Dynamic forms from angular with the help of FormBuild 
https://angular.io/guide/dynamic-form

**Comment by sumitmatta998** [comment]
@KhaledSMQ @pankajk2934 do we need to write custom parser of this JSON, or is there any tool which are supporting the same JSON. (rendered for the particular project)

**Comment by KhaledSMQ** [comment]
@sumitmatta998 for me i have build custom JSON to map the elements with form build.
